### ISSUE TITLE
Regarding auto code redeem

### ISSUE THREAD

**Issue by Capoouo** [torikushiii/hoyolab-auto#47] opened 2024-08-07 03:05 UTC
I’m not sure if it’s a bug. My config for Genshin-Impact auto code redeem is set to true. Additionally, the control panel shows 
2024-08-06 22:49:00 hoyolab-auto | 2024-08-06 22:49:00 <INFO:GenshinResolver> Found 1 new codes 
but my Discord webhook hasn’t received any information about the redemption

**Comment by torikushiii** [comment] 2024-08-07 10:25
Thank you for pointing this out! The issue was caused by an incorrect property name, which led the parser to ignore it (but still redeems the code regardless) and not send it to notifications. This has been fixed in the latest commit.

**Closed by torikushiii** 2024-08-07 10:25 UTC
