### ISSUE TITLE
code redeem

### ISSUE THREAD

**Issue by Capoouo** [torikushiii/hoyolab-auto#66] opened 2024-10-01 03:34 UTC
Hi, I encountered the same issue again. During the Genshin 5.0 code redemption, there were two instances of finding codes, but only one was redeemed. Additionally, today there is a new code for StarRail:

2024-10-01 10:45:00 hoyolab-auto | 2024-10-01 10:45:00 [INFO:StarRailResolver] Found 1 new codes

After discovering that it wasn’t redeemed, I tried deleting the cache and restarting Docker. Then the following message appeared:

2024-10-01 11:30:01 hoyolab-auto | 2024-10-01 11:30:01 [INFO:StarRailResolver]Found 1 new codes

However, there were no messages on Discord, and no errors were indicated in the control panel

edit: 
I tried deleting the cache and the new code again, and after restarting, the redemption worked normally. Weird

**Comment by torikushiii** [comment] 2024-10-01 15:01
I've pushed a potential fix for this, but for this specific issue, I’m leaning more towards a timeout problem that I probably haven’t handled correctly. Do let me know!

**Comment by torikushiii** [comment] 2024-10-01 17:52
![image](https://github.com/user-attachments/assets/4f5263c7-2853-42b2-8376-fe4546db6908)

hmm, im not exactly sure what causing this because all so far code redemption is working fine for me, but I'll try think of something

**Comment by torikushiii** [comment] 2024-10-01 17:56
![image](https://github.com/user-attachments/assets/1832c6c5-c157-4247-a962-f053bcdb685e)

hmm, im not sure exactly what is causing this, but so far all my code redemption work fine so far, but ill try to think of something (the reason for that redemption error is because you can't redeem this code from web)

**Comment by torikushiii** [comment] 2024-10-02 09:08
there's a new update that i pushed last night and forgot to tell you here, did you use it?

**Comment by torikushiii** [comment] 2024-10-04 06:49
![image](https://github.com/user-attachments/assets/6cad49a5-badb-4609-984a-2be352cb6997)

for me it redeemed fine so far.

go to your index.js which is this one https://github.com/torikushiii/hoyolab-auto/blob/main/index.js

and comment out or remove this piece of code and let it run until there's new code to see if there's any error

https://github.com/torikushiii/hoyolab-auto/blob/476f3476cff92903c1d5a9426585f48919d44ee7/index.js#L117-L126

**Comment by torikushiii** [comment] 2024-10-05 11:08
ah, so it's indeed network error related.

this can be caused by underlying network connectivity or if your Docker container is resource-constrained (for example, if it has limited CPU or memory allocated)

**Comment by torikushiii** [comment] 2024-10-05 11:36
you can try to see if its help with the current issue, but im pretty sure 2 cores with 4GB memory is more than enough

**Comment by torikushiii** [comment] 2024-10-05 15:06
should be fixed on latest commit

**Comment by torikushiii** [comment] 2024-10-06 11:05
I'm still leaning towards connection timed out issues, but if the next code redemption has the same result, I'll try adding internal retries in case the request doesn't "respond".

**Comment by torikushiii** [comment] 2024-10-08 11:21
I've pushed new commit to change on how the redemption work, i don't know if this will help because i still didn't know how to replicate this problem yet.

**Comment by torikushiii** [comment] 2024-10-10 14:20
Yes that error can be ignored.

**Comment by torikushiii** [comment] 2024-10-10 16:50
no, they changeg the check-in url, i will deploy a fix later

**Comment by torikushiii** [comment] 2024-10-11 05:37
You could try commenting that line out again to see if it prints any messages, the reason it was there because there's already a custom error handler.

But next time I'll try to put debug log at that line in the future.

**Comment by torikushiii** [comment] 2024-10-11 05:49
No need

**Comment by torikushiii** [comment] 2024-10-11 12:06
can you try pulling the latest commit and let me know, I've added few logs to it

**Comment by torikushiii** [comment] 2024-10-11 12:23
hold on, i think i can replicate this issue now

**Comment by torikushiii** [comment] 2024-10-11 13:11
of course when I encountered this issue it resolve itself for some reason...

try pulling the latest commit and change the loglevel to debug, `loglevel: "debug"` at config this time, don't forget to remove the last 3 codes if any of the account haven't redeemed any

**Comment by torikushiii** [comment] 2024-10-11 13:18
that's fine, just remember to change loglevel to debug if you encountered this again to see if there's any message at all

**Comment by torikushiii** [comment] 2024-10-11 13:38
You can either set the log level to debug until the next new code release or set the log level to debug after there's new code and it didn't redeem the code if you didn't want your log to get spammed by debug messages.

**Comment by NaufalF22** [comment] 2024-10-14 02:19
![image](https://github.com/user-attachments/assets/24bff605-506a-4c6f-9eff-f361d3b08843)
Its work now but theres 2 code every 5 sec (idk you can do this or not)

**Comment by reticence96** [comment] 2024-10-23 10:27
None of the new Star Rail codes were redeemed, as each of the codes had NEW added to the end of the code.

"Star Rail - New codes found: RAPPANINJADICTNEW, MISTERRATIONEW, EB3KUYQW833PNEW"

**Comment by torikushiii** [comment] 2024-10-23 11:28
those 3 codes has expired hours ago, so there's no notification will be send.

**Comment by torikushiii** [comment] 2024-10-23 12:18
oh yeah...

![image](https://github.com/user-attachments/assets/00756a86-ba7e-44a2-bf85-16db2b9545c2)

the API returns an invalid codes 🙃

**Comment by torikushiii** [comment] 2024-10-23 14:06
sorry for the confusion earlier, talked to the guy managed the API and he fixed it, should be all good now 👍 

![image](https://github.com/user-attachments/assets/1cabb707-bb20-4c11-9824-f2e27aab2a78)

**Comment by torikushiii** [comment] 2024-10-23 14:42
yes, it is safe to comment out the lines.

**Comment by torikushiii** [comment] 2024-11-12 10:47
@Capoouo sorry for the late reply. I was working on [hoyoverse-api](https://github.com/torikushiii/hoyoverse-api) during this whole weekend so this program can use this API instead letting the users scraping the website by themselves.

Now I've rewritten the code redeemer to use the new API and the whole code redeemer function, please update and try again.

Just a quick reminder that the saving to cache method is reworked and old cache need to be deleted.

**Closed as completed** 2024-11-22 12:15 UTC

**Comment by torikushiii** [comment] 2024-12-09 05:30
@Capoouo yes, sorry about that, my server went down for a moment but all should be good now.
